full_country_list = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas, The",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Caribbean small states",
    "Central African Republic",
    "CERN",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo Dem. Rep.",
    "Congo Rep.",
    "Costa Rica",
    "Cote d'Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Denmark",
    "DESY",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt, Arab Rep.",
    "El Salvador",
    "Equatorial Guinea",
    "Estonia",
    "Ethiopia",
    "FERMILAB",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hong Kong SAR, China",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran, Islamic Rep.",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "JINR",
    "Jordan",
    "Kazakhstan",
    "KEK",
    "Kenya",
    "Kiribati",
    "Kosovo",
    "Kuwait",
    "Kyrgyz Republic",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Lithuania",
    "Luxembourg",
    "Macao SAR China",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia Fed. Sts.",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "Norway",
    "Oman",
    "Other small states",
    "Pakistan",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Puerto Rico",
    "Qatar",
    "San Marino",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "Samoa",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "SLAC",
    "Slovak Republic",
    "Slovenia",
    "Solomon Islands",
    "South Africa",
    "Korea, Rep.",
    "Spain",
    "Sri Lanka",
    "St. Kitts and Nevis",
    "St. Lucia",
    "St. Vincent and the Grenadines",
    "Sudan",
    "Suriname",
    "Swazilend",
    "Sweden",
    "Switzerland",
    "Syrian Arab Republic",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkiye",
    "Turkmenistan",
    "Uganda",
    "United Kingdom",
    "Ukraine",
    "United Arab Emirates",
    "Uruguay",
    "United States",
    "Uzbekistan",
    "Venezuela, RB",
    "Vietnam",
    "West Bank and Gaza",
    "Yemen, Rep.",
    "Zambia",
    "Zimbabwe",
    "UNKNOWN",
]

countries_mapping = {
    "Palestine": "West Bank and Gaza",
    "HUMAN CHECK": "UNKNOWN",
    "México": "Mexico",
    "The Bahamas": "Bahamas, The",
    "Bahamas": "Bahamas, The",
    "United States of America": "United States",
    "USA": "United States",
    "Russia": "Russian Federation",
    "Egypt": "Egypt, Arab Rep.",
    "UK": "United Kingdom",
    "South Korea": "Korea, Rep.",
    "Iran": "Iran, Islamic Rep.",
    "Hong Kong": "Hong Kong SAR, China",
    "Turkey": "Turkiye",
    "Czech Republic": "Czechia",
    "Slovakia": "Slovak Republic",
    "Venezuela": "Venezuela, RB",
    "Syria": "Syrian Arab Republic",
}
